<a href="https://colab.research.google.com/github/ahmdbnrsl/From-Python-to-ML/blob/main/MATH/mathematics_ML.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
pip install numpy

Vector space (ruang vektor) adalah sebuah himpunan (kumpulan objek) yang:

1. Anggotanya disebut vektor


2. Memenuhi dua operasi utama:

Penjumlahan vektor: menambahkan dua vektor menghasilkan vektor baru.

Perkalian skalar: mengalikan vektor dengan bilangan (skalar) menghasilkan vektor baru juga.



3. Tunduk pada 8 aturan (aksioma) tertentu (kita bahas nanti).



Biasanya ruang vektor ini didefinisikan di atas field (seperti bilangan real ℝ atau bilangan kompleks ℂ), artinya semua skalarnya berasal dari field itu.

Kalau ada dua vektor u = (u₁, u₂) dan v = (v₁, v₂), maka:

Penjumlahan vektor:
u + v = (u₁ + v₁, u₂ + v₂)

Perkalian skalar dengan bilangan k:
k * u = (k * u₁, k * u₂)

8 Aksioma Ruang Vektor

1. Asosiatif penjumlahan: (u + v) + w = u + (v + w)


2. Komutatif penjumlahan: u + v = v + u


3. Elemen nol: Ada vektor 0, sehingga u + 0 = u


4. Elemen invers aditif: Untuk setiap u, ada -u, sehingga u + (-u) = 0


5. Asosiatif perkalian skalar: a(bu) = (ab)u


6. Identitas skalar: 1 * u = u


7. Distributif terhadap penjumlahan vektor: a(u + v) = au + av


8. Distributif terhadap penjumlahan skalar: (a + b)u = au + bu



Kalau semua ini terpenuhi, maka himpunan itu adalah vector space.

In [ ]:
import numpy as np

def is_vector_space_check(vecs):
    # Cek penjumlahan
    u = vecs[0]
    v = vecs[1]
    sum_vec = u + v
    print(f"u + v = {sum_vec}")

    # Cek perkalian skalar
    k = 3
    scaled_vec = k * u
    print(f"{k} * u = {scaled_vec}")

vecs = [np.array([1, -1]), np.array([-2, 2])]  # x + y = 0
vecs_1 = [np.array([2, 1]), np.array([4, 2])]  # x = 2y
vecs_2 = [np.array([2, 4]), np.array([4, 6])]  # x + 2 = y

is_vector_space_check(vecs)
is_vector_space_check(vecs_2)

u + v = [-1  1]
3 * u = [ 3 -3]
u + v = [ 6 10]
3 * u = [ 6 12]


In [ ]:
def is_vector_space_check(vecs):
    u = vecs[0]
    v = vecs[1]

    sum_vec = u + v
    scaled_vec = 3 * u

    def is_in_V(vec):
        return np.sum(vec) == 0

    if is_in_V(sum_vec) and is_in_V(scaled_vec):
        print("✅ Ini adalah vector space")
        return True
    else:
        print("❌ Ini bukan vector space")
        return False

is_vector_space_check([np.array([5, 2, 1]), np.array([10, 4, 2])])

❌ Ini bukan vector space


False

Euclidean Space (Ruang Euclidean)




Euclidean space adalah ruang vektor berdimensi-n yang dilengkapi dengan konsep jarak dan sudut.

1. Dot Product (Perkalian Titik) menghasilkan scalar
2. Norm (Panjang/Modulus)
3. Distance (Jarak)
4. Sudut antara dua vektor

In [ ]:

import numpy as np
from math import sqrt, acos, degrees

# Diberikan vektor
a = np.array([2, -1, 4])
b = np.array([-3, 0, 1])

# Pertanyaan:
# 5.1 Hitung dot product a · b
print(a @ b)
# 5.2 Hitung panjang dari vektor a
print(sqrt(np.sum(i**2 for i in a)))
# 5.3 Hitung jarak antara a dan b
print(sqrt(np.sum(i**2 for i in a - b)))
# 5.4 Hitung sudut antara a dan b (dalam derajat)
cos_theta = (a @ b) / (np.linalg.norm(a) * np.linalg.norm(b))
theta_rad = acos(cos_theta)
theta_deg = degrees(theta_rad)
print(theta_deg)

-2
4.58257569495584
5.916079783099616
97.93288986424014


<ipython-input-19-1293192234>:12: DeprecationWarning: Calling np.sum(generator) is deprecated, and in the future will give a different result. Use np.sum(np.fromiter(generator)) or the python sum builtin instead.
  print(sqrt(np.sum(i**2 for i in a)))
<ipython-input-19-1293192234>:14: DeprecationWarning: Calling np.sum(generator) is deprecated, and in the future will give a different result. Use np.sum(np.fromiter(generator)) or the python sum builtin instead.
  print(sqrt(np.sum(i**2 for i in a - b)))


Subspace
Subspace (ruang bagian) adalah subset dari vector space yang juga merupakan vector space itu sendiri.

In [ ]:
# langkah 1 menentukan subspace
# cek apakah 0 vektor memenuhi syarat himpunan

v = np.array([1, 2]) # y = 2x
v0 = np.array([0, 0]) # y = 2x -> yaa betull

# tinggal kita cek bagian dari vector space apa bukan
def is_subspace(vecs):

    rule = v0[1] == v0[0]**2

    if rule:
        print("nol vektor valid")
        if is_vector_space_check(vecs): print("Ini vektor subspaces")
        else: print("Ini bukan vektor subspaces")

is_subspace([np.array([2, 4]), np.array([4, 16])])

nol vektor valid
❌ Ini bukan vector space
Ini bukan vektor subspaces


Linear Maps

A. Menerima vektor sebagai input

B. Mengembalikan vektor sebagai output (di ruang vektor tujuan)

C. Dan harus memenuhi 3 properti utama:

🔹 1. Memetakan nol vektor ke nol vektor
🔹 2. Additivity (penjumlahan)
🔹 3. Homogeneity (perkalian skalar)

In [ ]:
# fungsi untuk menentukan linear map
import numpy as np
v0 = np.array([0,0])
u = np.array([1, 2])
v_ = np.array([2, 4])

def a(v):
    return np.array([v[0] + v[1], v[0] - v[1]])
def b(v):
    return np.array([v[0] + 1, v[1]])
def c(v):
    return np.array([v[0] ** 2, v[1]])
def d(v):
    return 5 * v
def e(v):
    return 0 * v

# 1.

print("1")
print(np.equal(v0, a(v0)))
print(np.equal(a(u + v_), a(u) + a(v_)))
print(np.equal(a(2 * u), 2 * a(u)))

# 2.

print("2")
print(np.equal(v0, b(v0)))
print(np.equal(b(u + v_), b(u) + b(v_)))
print(np.equal(b(2 * u), 2 * b(u)))


# 3.

print("3")
print(np.equal(v0, c(v0)))
print(np.equal(c(u + v_), c(u) + c(v_)))
print(np.equal(c(2 * u), 2 * c(u)))

# 4.

print("4")
print(np.equal(v0, d(v0)))
print(np.equal(d(u + v_), d(u) + d(v_)))
print(np.equal(d(2 * u), 2 * d(u)))

# 5.

print("5")
print(np.equal(v0, e(v0)))
print(np.equal(e(u + v_), e(u) + e(v_)))
print(np.equal(e(2 * u), 2 * e(u)))


# Exercise

v0 = np.array([0,0])
u = np.array([1, 2])
v_ = np.array([2, 4])

def T(v):
    return np.array([2 * v[0] + v[1], v[0] - 3 * v[1]])

print(np.equal(v0, T(v0)))
print(np.equal(T(u + v_), T(u) + T(v_)))
print(np.equal(T(2 * u), 2 * T(u)))

1
[ True  True]
[ True  True]
[ True  True]
2
[False  True]
[False  True]
[False  True]
3
[ True  True]
[False  True]
[False  True]
4
[ True  True]
[ True  True]
[ True  True]
5
[ True  True]
[ True  True]
[ True  True]
[ True  True]
[ True  True]
[ True  True]


Linear operator

Linear operator adalah linear maps yang domain dan kodomainnya (input-output) nya di ruang vektor yang sama

In [ ]:
# contoh Linear operator

def lo(v):
    return np.array([v[0] * 2, v[1] * 2])

v0 = np.array([0,0])
u = np.array([1, 2])
v_ = np.array([2, 4])

print(np.equal(v0, lo(v0)))
print(np.equal(lo(u + v_), lo(u) + lo(v_)))
print(np.equal(lo(2 * u), 2 * lo(u)))

[ True  True]
[ True  True]
[ True  True]


Matrics of linear maps

Ini adalah representasi matriks yang jika di lakukan dot product dengan domain (input) dari linear maps akan menghasilkan output (kodomain) yang sama dari linear maps itu sendiri.


langkah langkah menentukannya adalah dengan memasukan basis kanonik sebagai domain dari linear maps,

basis kanonik adalah vektor yang berisi 1 dan 0 dimana jika vektor tersebut digabungkan sebagai kolom2 matriks maka angka satu nya akan membentuk diagonal alias matriks identitas

R^n -> e^n
artinya jika vector n x 1 maka kanonik nya n × n

In [ ]:
def mlo(v):
    return np.array([v[0] + v[1], v[1] + v[2]])

def mlo_2(v):
    return np.array([[1, 1, 0], [0, 1, 1]]) @ v

v3 = np.array([1, 2, 3])
print(mlo_2(v3))
print(mlo(v3))
# masukan basis kanonik

kanonik_base = np.array([
    [1, 0, 0],
    [0, 1, 0],
    [0, 0, 1]
])

def create_matriks_from_lm(lm, input_length):
    kanonik_base = np.identity(input_length)
    length = len(kanonik_base)
    return np.array([lm(kanonik_base[:, i]) for i in range(length)]).T



print(mlo(kanonik_base[:, 0])) # ini akan menghasil kan vektor kolom yang akan digunakan untuk menyusun matriks
print(mlo(kanonik_base[:, 1]))
print(mlo(kanonik_base[:, 2]))
create_matriks_from_lm(mlo, len(v3))

[3 5]
[3 5]
[1 0]
[1 1]
[0 1]


array([[1., 1., 0.],
       [0., 1., 1.]])

In [ ]:
np.identity(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

Row Echelon


Langkah pengerjaan

tentukan pivot di elemen pertama dari baris 1 selama elemen noon 0, naahh trus baarris bawahnya kita tentukan pivot dikali berapa suppaya hasilnya pivot dibaris itu..., jika pivot di R1 0 maka tukar baris, jika pivot di elemen paling bawah sudah 0 maka geser kekanan, lalu tentukan tangga eselon

contoh soal :


Nomor 1.
[1, 2]
[3, 4]

R2 = R2 - 3R1 => [3, 4] - 3 * [1, 2] =  [0, -2]

Nomor 2.
[0, 2, 3]
[ 1, 1, 1 ]
[2, 4, 6]

tukar baris 1 dan 2
[1, 1, 1]
[0, 2, 3]
[2, 4, 6]

eliminasi baris 3
R3 = R3 - 2R1 => [2, 4, 6] - 2 * [1, 1, 1] = [0, 2, 4]

baris 3 kita kurang kan dengan baris 2
R3 = R3 - R2 = [0, 0, 1]

maka hasilnya
[1,1,1]
[0, 2,3]
[0,0, 1]

Nomor 3.
[2,4,6]
[1,2,3]
[0,0,1]

R2 = R2 - 1/2R1 => [1,2,3] - 1/2*[2, 4, 6] => [0, 0, 0]

kita tukar baris 2 dan 3
maka hasilnya

[2,4,6]
[0,0,1]
[0,0,0]

In [13]:
import numpy as np

def row_echelon(matrix):
    A = matrix.astype(float)
    m, n = A.shape
    print(m, n)
    row = 0
    for col in range(n):
        if row >= m:
            break
        # Cari pivot (baris dengan nilai terbesar di kolom saat ini)
        max_row = np.argmax(abs(A[row:, col])) + row
        print(np.argmax(abs(A[row:, col])))
        if A[max_row, col] == 0:
            continue
        # Tukar baris
        A[[row, max_row]] = A[[max_row, row]]
        # Normalisasi pivot
        A[row] = A[row] / A[row, col]
        # Eliminasi baris bawah
        for r in range(row + 1, m):
            A[r] = A[r] - A[r, col] * A[row]
        row += 1
    return A

A = np.array([
    [0, 1, 2],
    [1, 1, 1],
    [2, 4, 5],
    [1, 2, 3]
])

row_echelon(A)

4 3
2
0
0


array([[ 1. ,  2. ,  2.5],
       [-0. ,  1. ,  1.5],
       [ 0. ,  0. ,  1. ],
       [ 0. ,  0. ,  0. ]])

Span

Span dari suatu himpunan vektor adalah seluruh kumpulan vektor yang bisa dibentuk dari kombinasi linear dari vektor-vektor tersebut.

cara menentukan nya adalah dengan menentukan skalar * v1 + skalar * v2 = t

cari skalar yang memenuhi, jika tidak ada skalar yang memenuhi maka t bukan bagian dari span

contoh

1. apakah t = [4, 5] ada dalam span [1, 2], [2, 1]



c1 + 2c2 = 4

2c1 + c2 = 5

c1 = 4 - 2c2 (i)


2(4 - 2c2) + c2 = 5

8 - 4c2 + c2 = 5

8 - 3c2 = 5

8 = 5 + 3c2

8 = 5 + 3(1)

c2 = 1


subtitusi ke (i)

4 - 2(1) = 2

c1 = 2


jadi t ada dalam span


2. apakah t = [2, 3, 1] ada dalam span  [1, 0, -1], [0, 1, 1]



c1 + 0 = 2

0 + c2 = 3

-c1 + c2 = 1

-2 + 3 = 1


t ada dalam span


3. apakah t = [1, 2, 4] ada dalam span [1,2,3], [2,4,6]



c1 + 2c2 = 1

2c1 + 4c2 = 2

3c1 + 6c2 = 4

c1 = 1 - 2c2 (i)

2(1 - 2c2) + 4c2 = 2

2 - 4c2 + 4c2 = 2

2 - 8c2 = 2

2 - 8(0) = 2


c2 = 0 (ii)

c1 = 1 - 2(0) = 1

3(1) + 0 != 4

jadi t tidak berada dalam span

In [ ]:

import numpy as np

def is_in_span(vectors, target):
    import numpy as np
    A = np.column_stack(vectors)
    print(A)
    try:
        x = np.linalg.lstsq(A, target, rcond=None)[0]
        print(x)
        print(A @ x)
        return np.allclose(A @ x, target)
    except:
        return False

span = np.array([
    [1, 0, -1],
    [0, 1, 1]
])

t = np.array([2, 3, 1])

print(span @ t)

is_in_span(span, t)

[1 4]
[[ 1  0]
 [ 0  1]
 [-1  1]]
[2. 3.]
[2. 3. 1.]


True

Null Space

jadiii intinya null space tuh menggenerate span (x) untuk yg jika dikalikan dengan baris2 matriks A menjadi vektor 0

contoh :

A1 = [[1, 2, -1], [2, 4, -2]]

x1 + 2x2 - x3 = 0

2x1 + 4x2 - 2x3 = 0

eliminasi row echelon

R2 - 2R1 = [[1, 2, -1], [0, 0, 0]]

expresikan variable bebas

x1 + 2x2 - x3 = 0 => x1 = -2x2 + x3

var bebas: x2, x3

x = [-2x2 + x3, x2, x3] = x2 [-2, 1, 0] + x3 [1, 0, 1]

null(A1) = span{[-2, 1, 0], [1,0,1]

A2 = [[1, -1, 2], [3, -3, 6]

eliminasi row echelon

R2 - 3R1 = [[1, -1, 2], [0, 0, 0]

x1 - x2 + 2x3 = 0

x1 = x2 - 2x3

expresikan =>

[x2 - 2x3, x2, x3] =>

null(A2) = span{[1, 1, 0], [-2, 0, 1]}

A3 = [[1, 2, 1], [0, 1, 1]]

x1 + 2x2 + x3 = 0

x2 + x3 = 0

x2 = -x3

x1 = -2(-x3) - x3  = x3

[x3, -x3, x3]

[1, -1, 1]

In [26]:
pip install scipy sympy

In [44]:

import numpy as np
from scipy.linalg import null_space

A = np.array([
    [1,2,1],
    [0,1,1]
])

print(null_space(A))

[[ 0.57735027]
 [-0.57735027]
 [ 0.57735027]]


Range