<a href="https://colab.research.google.com/github/ahmdbnrsl/From-Python-to-ML/blob/main/MATH/mathematics_ML.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

BAB 1. LINEAR ALGEBRA

In [ ]:
pip install numpy


A. VECTOR SPACE

Vector space (ruang vektor) adalah sebuah himpunan (kumpulan objek) yang:

1. Anggotanya disebut vektor


2. Memenuhi dua operasi utama:

Penjumlahan vektor: menambahkan dua vektor menghasilkan vektor baru.

Perkalian skalar: mengalikan vektor dengan bilangan (skalar) menghasilkan vektor baru juga.



3. Tunduk pada 8 aturan (aksioma) tertentu (kita bahas nanti).



Biasanya ruang vektor ini didefinisikan di atas field (seperti bilangan real ℝ atau bilangan kompleks ℂ), artinya semua skalarnya berasal dari field itu.

Kalau ada dua vektor u = (u₁, u₂) dan v = (v₁, v₂), maka:

Penjumlahan vektor:
u + v = (u₁ + v₁, u₂ + v₂)

Perkalian skalar dengan bilangan k:
k * u = (k * u₁, k * u₂)

8 Aksioma Ruang Vektor

1. Asosiatif penjumlahan: (u + v) + w = u + (v + w)


2. Komutatif penjumlahan: u + v = v + u


3. Elemen nol: Ada vektor 0, sehingga u + 0 = u


4. Elemen invers aditif: Untuk setiap u, ada -u, sehingga u + (-u) = 0


5. Asosiatif perkalian skalar: a(bu) = (ab)u


6. Identitas skalar: 1 * u = u


7. Distributif terhadap penjumlahan vektor: a(u + v) = au + av


8. Distributif terhadap penjumlahan skalar: (a + b)u = au + bu



Kalau semua ini terpenuhi, maka himpunan itu adalah vector space.

In [ ]:
import numpy as np

def is_vector_space_check(vecs):
    # Cek penjumlahan
    u = vecs[0]
    v = vecs[1]
    sum_vec = u + v
    print(f"u + v = {sum_vec}")

    # Cek perkalian skalar
    k = 3
    scaled_vec = k * u
    print(f"{k} * u = {scaled_vec}")

vecs = [np.array([1, -1]), np.array([-2, 2])]  # x + y = 0
vecs_1 = [np.array([2, 1]), np.array([4, 2])]  # x = 2y
vecs_2 = [np.array([2, 4]), np.array([4, 6])]  # x + 2 = y

is_vector_space_check(vecs)
is_vector_space_check(vecs_2)

u + v = [-1  1]
3 * u = [ 3 -3]
u + v = [ 6 10]
3 * u = [ 6 12]


In [ ]:
def vector_space_check(vecs):
    u = vecs[0]
    v = vecs[1]

    sum_vec = u + v
    scaled_vec = 3 * u

    def is_in_V(vec):
        return np.sum(vec) == 0

    if is_in_V(sum_vec) and is_in_V(scaled_vec):
        print("✅ Ini adalah vector space")
        return True
    else:
        print("❌ Ini bukan vector space")
        return False

vector_space_check([np.array([5, 2, 1]), np.array([10, 4, 2])])

❌ Ini bukan vector space


False

B. Euclidean Space (Ruang Euclidean)




Euclidean space adalah ruang vektor berdimensi-n yang dilengkapi dengan konsep jarak dan sudut.

1. Dot Product (Perkalian Titik) menghasilkan scalar
2. Norm (Panjang/Modulus)
3. Distance (Jarak)
4. Sudut antara dua vektor

In [ ]:

import numpy as np
from math import sqrt, acos, degrees

# Diberikan vektor
a = np.array([2, -1, 4])
b = np.array([-3, 0, 1])

# Pertanyaan:
# 5.1 Hitung dot product a · b
print(a @ b)
# 5.2 Hitung panjang dari vektor a
print(sqrt(np.sum(i**2 for i in a)))
# 5.3 Hitung jarak antara a dan b
print(sqrt(np.sum(i**2 for i in a - b)))
# 5.4 Hitung sudut antara a dan b (dalam derajat)
cos_theta = (a @ b) / (np.linalg.norm(a) * np.linalg.norm(b))
theta_rad = acos(cos_theta)
theta_deg = degrees(theta_rad)
print(theta_deg)

-2
4.58257569495584
5.916079783099616
97.93288986424014


/tmp/ipython-input-4-1293192234.py:12: DeprecationWarning: Calling np.sum(generator) is deprecated, and in the future will give a different result. Use np.sum(np.fromiter(generator)) or the python sum builtin instead.
  print(sqrt(np.sum(i**2 for i in a)))
/tmp/ipython-input-4-1293192234.py:14: DeprecationWarning: Calling np.sum(generator) is deprecated, and in the future will give a different result. Use np.sum(np.fromiter(generator)) or the python sum builtin instead.
  print(sqrt(np.sum(i**2 for i in a - b)))


C. SUBSPACE

Subspace (ruang bagian) adalah subset dari vector space yang juga merupakan vector space itu sendiri.

In [ ]:
# langkah 1 menentukan subspace
# cek apakah 0 vektor memenuhi syarat himpunan

v = np.array([1, 2]) # y = 2x
v0 = np.array([0, 0]) # y = 2x -> yaa betull

# tinggal kita cek bagian dari vector space apa bukan
def is_subspace(vecs):

    rule = v0[1] == v0[0]**2

    if rule:
        print("nol vektor valid")
        if is_vector_space_check(vecs): print("Ini vektor subspaces")
        else: print("Ini bukan vektor subspaces")

is_subspace([np.array([2, 4]), np.array([4, 16])])

nol vektor valid
u + v = [ 6 20]
3 * u = [ 6 12]
Ini bukan vektor subspaces


D. LINEAR MAPS

A. Menerima vektor sebagai input

B. Mengembalikan vektor sebagai output (di ruang vektor tujuan)

C. Dan harus memenuhi 3 properti utama:

🔹 1. Memetakan nol vektor ke nol vektor
🔹 2. Additivity (penjumlahan)
🔹 3. Homogeneity (perkalian skalar)

In [ ]:
# fungsi untuk menentukan linear map
import numpy as np
v0 = np.array([0,0])
u = np.array([1, 2])
v_ = np.array([2, 4])

def a(v):
    return np.array([v[0] + v[1], v[0] - v[1]])
def b(v):
    return np.array([v[0] + 1, v[1]])
def c(v):
    return np.array([v[0] ** 2, v[1]])
def d(v):
    return 5 * v
def e(v):
    return 0 * v

# 1.

print("1")
print(np.equal(v0, a(v0)))
print(np.equal(a(u + v_), a(u) + a(v_)))
print(np.equal(a(2 * u), 2 * a(u)))

# 2.

print("2")
print(np.equal(v0, b(v0)))
print(np.equal(b(u + v_), b(u) + b(v_)))
print(np.equal(b(2 * u), 2 * b(u)))


# 3.

print("3")
print(np.equal(v0, c(v0)))
print(np.equal(c(u + v_), c(u) + c(v_)))
print(np.equal(c(2 * u), 2 * c(u)))

# 4.

print("4")
print(np.equal(v0, d(v0)))
print(np.equal(d(u + v_), d(u) + d(v_)))
print(np.equal(d(2 * u), 2 * d(u)))

# 5.

print("5")
print(np.equal(v0, e(v0)))
print(np.equal(e(u + v_), e(u) + e(v_)))
print(np.equal(e(2 * u), 2 * e(u)))


# Exercise

v0 = np.array([0,0])
u = np.array([1, 2])
v_ = np.array([2, 4])

def T(v):
    return np.array([2 * v[0] + v[1], v[0] - 3 * v[1]])

print(np.equal(v0, T(v0)))
print(np.equal(T(u + v_), T(u) + T(v_)))
print(np.equal(T(2 * u), 2 * T(u)))

1
[ True  True]
[ True  True]
[ True  True]
2
[False  True]
[False  True]
[False  True]
3
[ True  True]
[False  True]
[False  True]
4
[ True  True]
[ True  True]
[ True  True]
5
[ True  True]
[ True  True]
[ True  True]
[ True  True]
[ True  True]
[ True  True]


E. LINEAR OPERATOR

Linear operator adalah linear maps yang domain dan kodomainnya (input-output) nya di ruang vektor yang sama

In [ ]:
# contoh Linear operator

def lo(v):
    return np.array([v[0] * 2, v[1] * 2])

v0 = np.array([0,0])
u = np.array([1, 2])
v_ = np.array([2, 4])

print(np.equal(v0, lo(v0)))
print(np.equal(lo(u + v_), lo(u) + lo(v_)))
print(np.equal(lo(2 * u), 2 * lo(u)))

[ True  True]
[ True  True]
[ True  True]


F. Matrics of linear maps

Ini adalah representasi matriks yang jika di lakukan dot product dengan domain (input) dari linear maps akan menghasilkan output (kodomain) yang sama dari linear maps itu sendiri.


langkah langkah menentukannya adalah dengan memasukan basis kanonik sebagai domain dari linear maps,

basis kanonik adalah vektor yang berisi 1 dan 0 dimana jika vektor tersebut digabungkan sebagai kolom2 matriks maka angka satu nya akan membentuk diagonal alias matriks identitas

R^n -> e^n
artinya jika vector n x 1 maka kanonik nya n × n

In [ ]:
def mlo(v):
    return np.array([v[0] + v[1], v[1] + v[2]])

def mlo_2(v):
    return np.array([[1, 1, 0], [0, 1, 1]]) @ v

v3 = np.array([1, 2, 3])
print(mlo_2(v3))
print(mlo(v3))
# masukan basis kanonik

kanonik_base = np.array([
    [1, 0, 0],
    [0, 1, 0],
    [0, 0, 1]
])

def create_matriks_from_lm(lm, input_length):
    kanonik_base = np.identity(input_length)
    length = len(kanonik_base)
    return np.array([lm(kanonik_base[:, i]) for i in range(length)]).T



print(mlo(kanonik_base[:, 0])) # ini akan menghasil kan vektor kolom yang akan digunakan untuk menyusun matriks
print(mlo(kanonik_base[:, 1]))
print(mlo(kanonik_base[:, 2]))
create_matriks_from_lm(mlo, len(v3))

[3 5]
[3 5]
[1 0]
[1 1]
[0 1]


array([[1., 1., 0.],
       [0., 1., 1.]])

In [ ]:
np.identity(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

G. Row Echelon


Langkah pengerjaan

tentukan pivot di elemen pertama dari baris 1 selama elemen noon 0, naahh trus baarris bawahnya kita tentukan pivot dikali berapa suppaya hasilnya pivot dibaris itu..., jika pivot di R1 0 maka tukar baris, jika pivot di elemen paling bawah sudah 0 maka geser kekanan, lalu tentukan tangga eselon

contoh soal :


Nomor 1.
[1, 2]
[3, 4]

R2 = R2 - 3R1 => [3, 4] - 3 * [1, 2] =  [0, -2]

Nomor 2.
[0, 2, 3]
[ 1, 1, 1 ]
[2, 4, 6]

tukar baris 1 dan 2
[1, 1, 1]
[0, 2, 3]
[2, 4, 6]

eliminasi baris 3
R3 = R3 - 2R1 => [2, 4, 6] - 2 * [1, 1, 1] = [0, 2, 4]

baris 3 kita kurang kan dengan baris 2
R3 = R3 - R2 = [0, 0, 1]

maka hasilnya
[1,1,1]
[0, 2,3]
[0,0, 1]

Nomor 3.
[2,4,6]
[1,2,3]
[0,0,1]

R2 = R2 - 1/2R1 => [1,2,3] - 1/2*[2, 4, 6] => [0, 0, 0]

kita tukar baris 2 dan 3
maka hasilnya

[2,4,6]
[0,0,1]
[0,0,0]

In [ ]:
import numpy as np

def row_echelon(matrix):
    if not isinstance(matrix, np.ndarray):
        raise ValueError("masukan hanya matrix")
    A = matrix.astype(float)

    m, n = A.shape
    row = 0
    for col in range(n):
        if row >= m:
            break

        max_row = np.argmax(abs(A[row:, col])) + row

        if A[max_row, col] == 0:
            continue

        A[[row, max_row]] = A[[max_row, row]]

        A[row] = A[row] / A[row, col]

        for r in range(row + 1, m):
            A[r] = A[r] - A[r, col] * A[row]
        row += 1
    return A

Z = np.array([
    np.array([0, 1, 2]),
    np.array([1, 1, 1]),
    np.array([2, 4, 5])
])

row_echelon(np.array([
    [0, 1, 2],
    [1, 1, 1],
    [2, 4, 5]
]))

array([[ 1. ,  2. ,  2.5],
       [-0. ,  1. ,  1.5],
       [ 0. ,  0. ,  1. ]])

H. Span

Span dari suatu himpunan vektor adalah seluruh kumpulan vektor yang bisa dibentuk dari kombinasi linear dari vektor-vektor tersebut.

cara menentukan nya adalah dengan menentukan skalar * v1 + skalar * v2 = t

cari skalar yang memenuhi, jika tidak ada skalar yang memenuhi maka t bukan bagian dari span

contoh

1. apakah t = [4, 5] ada dalam span [1, 2], [2, 1]



c1 + 2c2 = 4

2c1 + c2 = 5

c1 = 4 - 2c2 (i)


2(4 - 2c2) + c2 = 5

8 - 4c2 + c2 = 5

8 - 3c2 = 5

8 = 5 + 3c2

8 = 5 + 3(1)

c2 = 1


subtitusi ke (i)

4 - 2(1) = 2

c1 = 2


jadi t ada dalam span


2. apakah t = [2, 3, 1] ada dalam span  [1, 0, -1], [0, 1, 1]



c1 + 0 = 2

0 + c2 = 3

-c1 + c2 = 1

-2 + 3 = 1


t ada dalam span


3. apakah t = [1, 2, 4] ada dalam span [1,2,3], [2,4,6]



c1 + 2c2 = 1

2c1 + 4c2 = 2

3c1 + 6c2 = 4

c1 = 1 - 2c2 (i)

2(1 - 2c2) + 4c2 = 2

2 - 4c2 + 4c2 = 2

2 - 8c2 = 2

2 - 8(0) = 2


c2 = 0 (ii)

c1 = 1 - 2(0) = 1

3(1) + 0 != 4

jadi t tidak berada dalam span

In [ ]:

import numpy as np

def is_in_span(vectors, target):
    A = np.column_stack(vectors)
    print(A)
    try:
        x = np.linalg.lstsq(A, target, rcond=None)[0]
        print(x)
        print(A @ x)
        return np.allclose(A @ x, target)
    except:
        return False

span = np.array([
    [1, 0, -1],
    [0, 1, 1]
])

t = np.array([2, 3, 1])

print(span @ t)

is_in_span(span, t)

[1 4]
[[ 1  0]
 [ 0  1]
 [-1  1]]
[2. 3.]
[2. 3. 1.]


True

I. Null Space

jadiii intinya null space tuh menggenerate span (x) untuk yg jika dikalikan dengan baris2 matriks A menjadi vektor 0

contoh :

A1 = [[1, 2, -1], [2, 4, -2]]

x1 + 2x2 - x3 = 0

2x1 + 4x2 - 2x3 = 0

eliminasi row echelon

R2 - 2R1 = [[1, 2, -1], [0, 0, 0]]

expresikan variable bebas

x1 + 2x2 - x3 = 0 => x1 = -2x2 + x3

var bebas: x2, x3

x = [-2x2 + x3, x2, x3] = x2 [-2, 1, 0] + x3 [1, 0, 1]

null(A1) = span{[-2, 1, 0], [1,0,1]

A2 = [[1, -1, 2], [3, -3, 6]

eliminasi row echelon

R2 - 3R1 = [[1, -1, 2], [0, 0, 0]

x1 - x2 + 2x3 = 0

x1 = x2 - 2x3

expresikan =>

[x2 - 2x3, x2, x3] =>

null(A2) = span{[1, 1, 0], [-2, 0, 1]}

A3 = [[1, 2, 1], [0, 1, 1]]

x1 + 2x2 + x3 = 0

x2 + x3 = 0

x2 = -x3

x1 = -2(-x3) - x3  = x3

[x3, -x3, x3]

[1, -1, 1]

In [ ]:
pip install scipy sympy

In [ ]:

import numpy as np
from scipy.linalg import null_space

Q = np.array([
    [1,2,1],
    [0,1,1]
])

print(null_space(Q))

[[ 0.57735027]
 [-0.57735027]
 [ 0.57735027]]


J. Range

span dari beberapa kolom asli matrix yang mengandung pivot di REF(matrix)

In [ ]:
def range_matrix(M):
    REF = row_echelon(M)
    span = []

    for i, e in enumerate(REF):
        for j, el in enumerate(REF[:, i]):
            if j >= i:
                if el != 0:
                    span.append(M[:, i])
                else: break

    return span

def range_matrix_2(M):
    REF = row_echelon(M)
    pivot_cols = []

    for row in REF:
        for i, val in enumerate(row):
            if abs(val) > 1e-8:  # toleransi float
                if i not in pivot_cols:
                    pivot_cols.append(i)
                break

    return [M[:, i] for i in pivot_cols]

M = np.array([
    [1, 2, 3],
    [2, 4, 6],
    [1, 1, 1]
])

print(range_matrix(M))
print(range_matrix_2(M))

[array([1, 2, 1]), array([2, 4, 1])]
[array([1, 2, 1]), array([2, 4, 1])]


K. Metric Space

Metric slace adalah pasangan (X, d) dimana X adalah himpunan bisa berupa Bilangan real, vektor, fungsi dan lain lain, dan d adalah : X * X = R => adalah fungsi jarak, atau distance function (Euclidian distance dll)

fungsi d harus memenuhi 4 syarat utama supaya bisa dikatakan metric

1. hasil nya Non negatif

2. identitas, dalam artian jika output dari fungsi 0, maka x = y

3. simetri, jika x, y == y, x

4. segitiga dalam artian d(x, z) < d(x,y) + d(y, z)

In [ ]:
from math import sqrt

def d1(x, y):
    return sqrt((x - y)**2)

def check_is_metric(d, x, y, z):
    non_negatif = d(x, y) >= 0
    identitas = d(1, 1) == 0
    simetri = d(x, y) == d(y, x)
    triangle = d(x, z) <= d(x,y) + d(y,z)
    if non_negatif and identitas and simetri and triangle:
        print("Ini adalah fungsi metric")
    else:
        print("ini bukan fungsi metric")

check_is_metric(d1, 2, 3, 4)

Ini adalah fungsi metric


L. Normed Spaces

Sebuah vector space (ruang vektor) yang dilengkapi dengan fungsi norm.



Fungsi norm adalah fungsi yang memetakan setiap vektor ke angka non-negatif, menggambarkan “panjang” atau “ukuran” dari vektor tersebut.

fungsi normed spaces harus memenuhi syarat

1. non-negatif output

2. homogenitas => norm(a * v) = a * norm(v)

3. triangle => norm(v + y) <= norm(v) + norm(y)


contoh fungsi norm yang terkenal ada

1. Manhattan / L1 norm

norm(v) = |v1| + |v2|

2. Euclidian Norm / L2 norm

norm(v) = sqrt(v1² + v2²)

3. Infinity norm

norm(v) = max(vi)

In [ ]:

import numpy as np
from math import sqrt

def l1_manhattan(v):
    return sum(abs(i) for i in v)

def l2_euclidian(v):
    return sqrt(sum(i**2 for i in v))

def check_is_normed_spaces(v, w, norm):
    non_negative = norm(v) >= 0
    homogenity = norm(v * 2) == 2 * norm(v)
    #w = np.random.randint(0, 9, len(v))
    triangle = norm(w + v) <= norm(w) + norm(v)

    if non_negative and homogenity and triangle:
        print("Ini adalah fungsi norm")
    else: print("Ini bukan fungsi norm")

vector = np.array([1, 2])
vector_2 = np.array([2, 4])

check_is_normed_spaces(vector, vector_2, l1_manhattan)
check_is_normed_spaces(vector, vector_2, l2_euclidian)

Ini adalah fungsi norm
Ini adalah fungsi norm


M.Inner Product spaces

Sebuah inner product space adalah vector space yang dilengkapi dengan operasi inner product (produk dalam), yaitu fungsi:

< . , . > : V × V => R

yang mengambil dua vektor dan mengembalikan bilangan real, dengan sifat-sifat tertentu.

1. Positif definit

dimana f(v, v) >= 0, dan jika f(u, u) = 0 maka u harus = 0 (vektor nol)

2. simetri

f(u, v) = f(v, u)

3. linearitas

f(a * u + w, v) = a * f(u, v) + f(w, v)

In [ ]:

import numpy as np

def func(v, w):
    return sum(e * w[i] for i, e in enumerate(v))

def func_1(v, w):
    return  v[0] * w[0] + 2 * v[1] * w[1]

def func_2(v, w):
    return v[0] * w[1] + v[1] * w[0]

def func_3(v, w):
    return 3 * v[0] * w[0] + 4 * v[1] * w[1] + 5 * v[2] * w[2]

def func_4(v, w):
    return sum(e**2 * w[i]**2 for i, e in enumerate(v))

def func_5(v, w):
    return v[0] * w[0] + v[1]

v_1 = np.array([1, -1])
v_2 = np.array([-2, 4])
v_3 = np.array([3, 6])

v_4 = np.array([1, -2, 1])
v_5 = np.array([4, -7, -4])

def check_is_inner_product(f, u, v, w):
    pd_1 = f(u, u) >= 0
    pd_2 = True

    if f(u,u) == 0: pd_2 = np.all(u == 0)

    simetry = f(v, u) == f(u, v)

    a = np.random.randint(1, 9)
    b = np.random.randint(-9, -1)

    left = f(a*u + b*v, w)
    right = a * f(u, w) + b * f(v, w)

    linearity = np.allclose(left, right)

    print("positive definite : ", pd_1 and pd_2)
    print("simetry : ", simetry)
    print("linearity : ", linearity)

    if pd_1 and pd_2 and simetry and linearity:
        return "Ini adalah inner product"
    else: return "Ini bukan inner product"

print("1\n")
print(check_is_inner_product(func, v_1, v_1, v_1))
print("2\n")
print(check_is_inner_product(func_2, v_1, v_1, v_3))
print("3\n")
print(check_is_inner_product(func_3, v_4, v_5, v_4))
print("4\n")
print(check_is_inner_product(func_4, v_1, v_2, v_3))
print("5\n")
print(check_is_inner_product(func_5, v_1, v_2, v_3))

1

positive definite :  True
simetry :  True
linearity :  True
Ini adalah inner product
2

positive definite :  False
simetry :  True
linearity :  True
Ini bukan inner product
3

positive definite :  True
simetry :  True
linearity :  True
Ini adalah inner product
4

positive definite :  True
simetry :  True
linearity :  False
Ini bukan inner product
5

positive definite :  False
simetry :  False
linearity :  True
Ini bukan inner product


kesimpulan berdasarkan penjelasan dan beberapa latihan diatas, jadii inner product sebuah fungsi yang menerima dua parameter (vektor) yang harus memenuhi syarat 1. positif definite dimana output harus >= 0 dan jika output 0 maka input harus vektor 0, kemudian yang kedua adalah simetry, dan yang ketiga adalah linearitas pada parameter pertama dimana left = f(a * u1 + b * u2, v) harus sama dengan right = a * f(u1, v) + b * f(u2, v)

Inner Product as Norm

|x| = √< x, x >

In [ ]:

from math import sqrt

def norm_IP(v):
    return sqrt(func_1(v, v))

norm_IP(np.array([1, 2]))

3.0

N.Ortoghonal dan Ortonormal

Ortoghonal adalah 2 buah vektor yang jika di kalikan (dot product) maka hasilnya 0

sedangkan Ortonormal adalah vektor ortogonal yang norm nya 1

In [ ]:
from math import sqrt

def norm(v):
    return sqrt(sum(i**2 for i in v))

def check_orto(u, v):
    ortogonal = u @ v == 0
    ortonormal = np.allclose(norm(u) + norm(v), 2)
    print("Ortogonal : ", ortogonal)
    print("Ortonormal : ", ortonormal)

u1 = np.array([1, 2])
v1 = np.array([2, -1])

u2 = np.array([0, 3, 4])
v2 = np.array([0, -4, 3])

u3 = np.array([3/5, 4/5])
v3 = np.array([4/5, -3/5])

u4 = np.array([1, 2, 2])
v4 = np.array([2, 1, -2])

u5 = np.array([1, 0, 0])
v5 = np.array([0, 1, 0])

print("1.")
check_orto(u1, v1)
print("2.")
check_orto(u2, v2)
print("3.")
check_orto(u3, v3)
print("4.")
check_orto(u4, v4)
print("5.")
check_orto(u5, v5)

1.
Ortogonal :  True
Ortonormal :  False
2.
Ortogonal :  True
Ortonormal :  False
3.
Ortogonal :  True
Ortonormal :  True
4.
Ortogonal :  True
Ortonormal :  False
5.
Ortogonal :  True
Ortonormal :  True


[Pythagorean Theorem]

Teorema Pythagoras yang terkenal secara alami dapat digeneralisasikan ke ruang produk dalam yang sewenang-wenang

teorema 1 => jika x ⊥ y (ortogonal) maka || x + y ||² = ||x||² + ||y||²

kemudian jika menggunakan norm inner product maka akan menghasil kan teorema dibawah ini

||x + y||² = <x +y, x + y> = <x,x> + <x, y> + <y, x> + <y,y> = ||x||² + ||y||²

In [ ]:
# pembuktian
import numpy as np
from math import sqrt

def norm(v):
    return sqrt(sum(i**2 for i in v))

x = np.array([1, 2, 2])
y = np.array([2, 1, -2])

np.allclose(norm(x + y)**2, norm(x)**2 + norm(y)**2)

True

O. Cauchy-Schwarz inequality

Nilai absolut dari hasil inner product dua vektor tidak pernah lebih besar dari hasil kali normanya.

|<u, v>| <= ||u|| * ||v||

In [ ]:

import numpy as np
from math import sqrt

def in_prod(v, w):
    return sum(e * w[i] for i, e in enumerate(v))

def norm(v):
    return sqrt(sum(i**2 for i in v))

u1, v1 = np.array([[1, 2], [2, 4]])
u2, v2 = np.array([[1, -1], [3, 5]])
u3, v3 = np.array([[2, 0, -1], [1, -1, 4]])
u4, v4 = np.array([[1, 1, 1], [-1, -1, -1]])
u5, v5 = np.array([[0, 1, 0], [1, 0, 0]])

print("\n")
print("1. ", abs(in_prod(u1, v1)), " <= ", norm(u1) * norm(v1))
print("2. ", abs(in_prod(u2, v2)), " <= ", norm(u2) * norm(v2))
print("3. ", abs(in_prod(u3, v3)), " <= ", norm(u3) * norm(v3))
print("4. ", abs(in_prod(u4, v4)), " <= ", norm(u4) * norm(v4))
print("5. ", abs(in_prod(u5, v5)), " <= ", norm(u5) * norm(v5))



1.  10  <=  10.000000000000002
2.  2  <=  8.246211251235321
3.  2  <=  9.486832980505138
4.  3  <=  2.9999999999999996
5.  0  <=  1.0



P. Ortoghonal Complement

orthogonal complement itu memang bisa di anggap "mirip dengan null space dari sistem dot product", tapi inputnya adalah kumpulan vektor, bukan matrix eksplisit seperti pada null space.

jadi tujuan dari ortoghonal complement adalah mencari vektor yang ortogonal terhadap semua subspace.

input nya harus jadi satu subspace

In [ ]:
import numpy as np
from scipy.linalg import null_space

span = np.array([
    [1,2,1],
    [0,1,1]
])

print(null_space(span))

[[ 0.57735027]
 [-0.57735027]
 [ 0.57735027]]


Q. Ortogonal Projection

jadiii intinya untuk proyeksi v ke vektor u atau vektor ke vektor tinggal kita subtitusikan aja ke rumusnya

proj_u(v) => u @ v / u @ u * u


sedangkan untuk proyeksi ke subspace maka subspace harus berisi vektor-vektor yang ortonormal

rumusnya : sigma (v @ ui) * ui

In [ ]:

import numpy as np

# proyeksi vektor v ke u
def proj_u(u, v):
    return (u @ v) / (u @ u) * u

u = np.array([1, 2])
v = np.array([2, 4])

proj_u(u, v)

# proyeksi vektor v ke subspace dengan basis ortonormal

def proj_w(v, span):
    return sum((v @ i) * i for i in span)

v = np.array([1, 2, 3])

span_ortonormal = np.array([
    [0, 1, 1],
    [1, 0, 0]
])

proj_w(v, span_ortonormal)

array([1, 5, 5])

Dekomposisi Ortogonal

vt = v - vs

In [ ]:
def ortogonal_dec(v, span):
    return v - proj_w(v, span)

v = np.array([1, 2, 3])

span_ortonormal = np.array([
    [1, 0, 0],
    [0, 1, 0]
])

ortogonal_dec(v, span_ortonormal)

array([0, 0, 3])

Proposition

(i) Rumus proyeksi ortogonal ke subspace

Ps(v) = sigma <v, si> * si

subspace harus basis ortonormal

In [ ]:

import numpy as np

# menentukan ortogonal lebih dari 2 vektor
def is_ortogonal(vectors):
    length = len(vectors)
    for index, vector in enumerate(vectors):
        for v in range(index, length):
            if index == v: continue
            ortogonal = np.allclose(vector @ vectors[v], 0)
            if not ortogonal: return False
    return True

def is_ortonormal(vectors):
    for v in vectors:
        ortonormal = np.allclose(np.linalg.norm(v), 1)
        if not ortonormal: return False
    return True

def gram_schmidt(vectors):
    ortogonals = []
    for v in vectors:
        w = v.copy()
        for u in ortogonals:
            proj = (u @ w) / (u @ u) * u
            w = w - proj
        if np.linalg.norm(w) > 1e-10:
            ortogonals.append(w / np.linalg.norm(w))
    return np.array(ortogonals)

def proj(v, s):
    if not (is_ortogonal(s) and is_ortonormal(s)):
        s = gram_schmidt(s)
    return sum((v @ si) * si for si in s)

# subspace harus ortonormal basis
S = np.array([[1, 0, 0], [0, 1, 0]])
v = np.array([2, 5, 3])

proj(v, S)

array([2, 5, 0])

(ii) Selisih antara vektor dan hasil proyeksi akan selalu ortogonal dengan Subruang nya

In [ ]:
# Pembuktian

selisih = v - proj(v, S)

for v in S:
    print("Ortogonal : ", is_ortogonal(np.array([selisih, v])))

Ortogonal :  True
Ortogonal :  True


(iii) proyeksi ke subruang adalah pemetaan linear

Ps(a.v + b.v) = a.Ps(a) + b.Ps(b)

In [ ]:
# Pembuktian

v = np.array([1, 2, 1])

print(np.allclose(proj(2 * v + 3 * v, S), 2 * proj(v, S) + 3 * proj(v, S)))

True


(iv) identitas didalam subspace

Ps(s) = s

In [ ]:
# Pembuktian

print(np.allclose(proj(S[1], S), S[1]))

True


(v)

1.Range(Ps) = S => hasil dari proyeksi akan berada di subspace S

2. null(Ps) = Ortogonal Complement of S

In [77]:
# Pembuktian 1

def is_in_subspace(vectors, target):
    A = np.column_stack(vectors)
    print(A)
    try:
        x = np.linalg.lstsq(A, target, rcond=None)[0]
        return np.allclose(A @ x, target)
    except:
        return False

def range_matrix_2(M):
    REF = row_echelon(M)
    pivot_cols = []

    for row in REF:
        for i, val in enumerate(row):
            if abs(val) > 1e-8:  # toleransi float
                if i not in pivot_cols:
                    pivot_cols.append(i)
                break

    return [M[:, i] for i in pivot_cols]

V = np.array([
    [1, 2, 3],
    [4, 5, 6]
])

S = np.array([
    [1, 1, 0],
    [1, -1, 0]
])

proj_result = []

for v in V:
    proj_result.append(proj(v, S))

print(proj_result)
print(np.array(proj_result).T)

result = range_matrix_2(np.array(proj_result).T)

print(result)
print(is_in_subspace(S, result[1]))

# Pembuktian 2
from scipy.linalg import null_space

print(null_space(np.array(proj_result)))
print(null_space(S))

[array([1., 2., 0.]), array([4., 5., 0.])]
[[1. 4.]
 [2. 5.]
 [0. 0.]]
[array([1., 2., 0.]), array([4., 5., 0.])]
[[ 1  1]
 [ 1 -1]
 [ 0  0]]
True
[[0.]
 [0.]
 [1.]]
[[0.]
 [0.]
 [1.]]


(vi) Ps² = Ps

artinya proyeksi itu idempotent

In [ ]:
# Pembuktian

print(proj(proj(v, S), S))
print(proj(v, S))

[2.96147404 2.75963149 3.34757119]
[2.96147404 2.75963149 3.34757119]


(vii) norma proyeksi lebih kecil dari norma v

In [ ]:
# Pembuktian

np.linalg.norm(proj(v, S)) <= np.linalg.norm(v)

np.True_

(viii) Proyeksi = Pendekatan terbaik

||v - Psv|| <= ||v - si||

In [ ]:
Psv_norm = np.linalg.norm(v - proj(v, S))

for i in S:
    print(Psv_norm <= np.linalg.norm(v - i))

True
True


R. Gram Schmidt

Gram-Schmidt adalah proses untuk mengubah sekumpulan vektor yang linier independen menjadi sekumpulan vektor yang:

Ortogonal satu sama lain

Kemudian dinormalisasi supaya panjangnya = 1 → menjadi ortonormal

note: jika hanya 1 vektor maka cukup lakukan v / norm(v) tidak perlu menggunakan gram-schmidt


rumus sederhana gram-schmidt adalah

misal input v1, v2, v3

cari u1 dengan u1 / norm(u1)

nahh lalu untuk langkah selanjutnya proyeksikan v2 ke u1, lalu u2 = v2 - proyeksi(u1, v2), lalu normalisasikan u2 / norm(u2)

lalu selanjutnya proyeksikan v3 ke u1 dan u2 lalu kurang kan u3 = v3 - proyeksi(u1, v3) - proyeksi(u2, v3) lalu normalisasikan u3 / norm(u3)

jika lebih dari ini maka lakukan langkah yang sama.

In [ ]:

import numpy as np
from math import sqrt

def check_orto(u, v):
    ortogonal = np.allclose(u @ v, 0)
    ortonormal = np.allclose(norm(u) + norm(v), 2)
    print("Ortogonal : ", ortogonal)
    print("Ortonormal : ", ortonormal)

def norm(v):
    return sqrt(sum(i**2 for i in v))

def gram_schmidt(v1, v2):
    u1 = v1
    norm_u1 = norm(u1)
    p_v2 = proj_u(u1 / norm_u1, v2)
    u2 = v2 - p_v2
    norm_u2 = norm(u2)

    return u1 / norm_u1, u2 / norm_u2

print("GRAM SCHMIDT")
u1, v1 = gram_schmidt(np.array([1, 2, 2]), np.array([2, 0, 2]))
print("1. ", u1, v1)
u2, v2 = gram_schmidt(np.array([1, 0, 1]), np.array([1, 1, 1]))
print("2. ", u2, v2)
u3, v3 = gram_schmidt(np.array([3, 1]), np.array([2, 2]))
print("3. ", u3, v3)
check_orto(u1, v1)
check_orto(u2, v2)
check_orto(u3, v3)

GRAM SCHMIDT
1.  [0.33333333 0.66666667 0.66666667] [ 0.66666667 -0.66666667  0.33333333]
2.  [0.70710678 0.         0.70710678] [0. 1. 0.]
3.  [0.9486833  0.31622777] [-0.31622777  0.9486833 ]
Ortogonal :  True
Ortonormal :  True
Ortogonal :  True
Ortonormal :  True
Ortogonal :  True
Ortonormal :  True


In [ ]:

import numpy as np

def gram_schmidt_2(vectors):
    ortogonals = []
    for v in vectors:
        w = v.copy()
        for u in ortogonals:
            print(u)
            proj = (u @ w) / (u @ u) * u
            w = w - proj
        if np.linalg.norm(w) > 1e-10:
            ortogonals.append(w / np.linalg.norm(w))
    return np.array(ortogonals)

u1, v1 = gram_schmidt_2(np.array([[3, 1], [2, 2]]))
print(u1, v1)
check_orto(u1, v1)

[0.9486833  0.31622777]
[0.9486833  0.31622777] [-0.31622777  0.9486833 ]
Ortogonal :  True
Ortonormal :  True
