<a href="https://colab.research.google.com/github/ahmdbnrsl/From-Python-to-ML/blob/main/DEEP_LEARNING/deep_learning.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
pip install numpy

In [ ]:
import numpy as np

# Input x berdimensi 3
x = np.array([1.0, -0.5, 2.0])

# Layer 1: 4 neuron hidden
W0 = np.random.randn(4, 3)
b0 = np.random.randn(4)
print(W0)
print(b0)

# Aktivasi
def relu(z):
    result = np.maximum(0, z)
    print(result)
    return result

# Layer 2: output neuron
W1 = np.random.randn(1, 4)
b1 = np.random.randn(1)

# Komputasi: Φ(x) = T1(σ(T0(x)))
z0 = W0 @ x + b0
print(x)          # T0(x)
a0 = relu(z0)             # σ
z1 = W1 @ a0 + b1         # T1
Phi_x = z1

print("Output Φ(x):", Phi_x)

[[-0.14226861  0.03218374  0.15325728]
 [ 1.11140483 -1.13766403 -1.22051775]
 [-0.52564745  0.74273405 -1.053749  ]
 [ 3.81941241  1.12807535  0.782141  ]]
[ 0.96196606 -0.81696822 -0.11541851  0.65314665]
[ 1.  -0.5  2. ]
[1.11012013 0.         0.         5.47280338]
Output Φ(x): [-3.75636183]


In [6]:
import numpy as np

# Fungsi aktivasi ReLU
def relu(x):
    return np.maximum(0, x)

# Input x ∈ R^6
x = np.random.randn(6)

# Bobot dan bias untuk layer pertama (T0)
W0 = np.random.randn(3, 6)  # 3 neuron, input 6
b0 = np.random.randn(3)

# Bobot dan bias untuk layer kedua (T1)
W1 = np.random.randn(2, 3)  # 2 output, 3 hidden neuron
b1 = np.random.randn(2)

# Forward pass
z0 = W0 @ x + b0        # Linear: T0(x)
h = relu(z0)            # Aktivasi: σ
z1 = W1 @ h + b1        # Linear: T1(h)
phi_x = z1              # Output akhir: Φ(x)

# Tampilkan hasil
print("Input x:", x)
print("Hidden activations (ReLU):", h)
print("Output Φ(x):", phi_x)

Input x: [ 0.79848492  1.71487191  0.1216531   1.42518709 -0.1444965   1.00680548]
Hidden activations (ReLU): [0.82989754 0.         1.76143369]
Output Φ(x): [1.14432309 1.83876147]
