<a href="https://colab.research.google.com/github/ahmdbnrsl/From-Python-to-ML/blob/main/DEEP_LEARNING/deep_learning.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
pip install numpy

In [ ]:
import numpy as np

# Input x berdimensi 3
x = np.array([1.0, -0.5, 2.0])

# Layer 1: 4 neuron hidden
W0 = np.random.randn(4, 3)
b0 = np.random.randn(4)
print(W0)
print(b0)

# Aktivasi
def relu(z):
    result = np.maximum(0, z)
    print(result)
    return result

# Layer 2: output neuron
W1 = np.random.randn(1, 4)
b1 = np.random.randn(1)

# Komputasi: Φ(x) = T1(σ(T0(x)))
z0 = W0 @ x + b0
print(x)          # T0(x)
a0 = relu(z0)             # σ
z1 = W1 @ a0 + b1         # T1
Phi_x = z1

print("Output Φ(x):", Phi_x)

[[-0.14226861  0.03218374  0.15325728]
 [ 1.11140483 -1.13766403 -1.22051775]
 [-0.52564745  0.74273405 -1.053749  ]
 [ 3.81941241  1.12807535  0.782141  ]]
[ 0.96196606 -0.81696822 -0.11541851  0.65314665]
[ 1.  -0.5  2. ]
[1.11012013 0.         0.         5.47280338]
Output Φ(x): [-3.75636183]


In [ ]:
import numpy as np

# Fungsi aktivasi ReLU
def relu(x):
    return np.maximum(0, x)

# Input x ∈ R^6
x = np.random.randn(6)

# Bobot dan bias untuk layer pertama (T0)
W0 = np.random.randn(3, 6)  # 3 neuron, input 6
b0 = np.random.randn(3)

# Bobot dan bias untuk layer kedua (T1)
W1 = np.random.randn(2, 3)  # 2 output, 3 hidden neuron
b1 = np.random.randn(2)

# Forward pass
z0 = W0 @ x + b0        # Linear: T0(x)
h = relu(z0)            # Aktivasi: σ
z1 = W1 @ h + b1        # Linear: T1(h)
phi_x = z1              # Output akhir: Φ(x)

# Tampilkan hasil
print("Input x:", x)
print("Hidden activations (ReLU):", h)
print("Output Φ(x):", phi_x)

Input x: [-0.28963866  0.7943598  -1.3579998  -0.01547925 -1.19580445 -0.02618481]
Hidden activations (ReLU): [0.        0.2745708 0.       ]
Output Φ(x): [0.65000194 0.3546503 ]


In [ ]:
import numpy as np

def relu(x):
    return np.maximum(0, x)

def relu_derivative(x):
    return (x > 0).astype(float)

def mse(y_true, y_pred):
    return np.mean((y_true - y_pred)**2)

def mse_derivative(y_true, y_pred):
    return 2 * (y_pred - y_true) / y_true.shape[0]

np.random.seed(0)
m, d, k = 100, 6, 2
X = np.random.randn(m, d)
Y = np.random.randn(m, k)

hidden_size = 3
W0 = np.random.randn(d, hidden_size) * 0.1
b0 = np.zeros((1, hidden_size))
W1 = np.random.randn(hidden_size, k) * 0.1
b1 = np.zeros((1, k))

lr = 0.01
epochs = 500

for epoch in range(epochs):
    Z1 = X @ W0 + b0
    A1 = relu(Z1)
    Z2 = A1 @ W1 + b1
    Y_pred = Z2

    loss = mse(Y, Y_pred)

    dZ2 = mse_derivative(Y, Y_pred)
    dW1 = A1.T @ dZ2
    db1 = np.sum(dZ2, axis=0, keepdims=True)
    dA1 = dZ2 @ W1.T
    dZ1 = dA1 * relu_derivative(Z1)
    dW0 = X.T @ dZ1
    db0 = np.sum(dZ1, axis=0, keepdims=True)

    W1 -= lr * dW1
    b1 -= lr * db1
    W0 -= lr * dW0
    b0 -= lr * db0

    if epoch % 50 == 0:
        print(f"Epoch {epoch}, Loss: {loss:.4f}")

Epoch 0, Loss: 0.9603
Epoch 50, Loss: 0.9454
Epoch 100, Loss: 0.9422
Epoch 150, Loss: 0.9400
Epoch 200, Loss: 0.9379
Epoch 250, Loss: 0.9354
Epoch 300, Loss: 0.9324
Epoch 350, Loss: 0.9287
Epoch 400, Loss: 0.9245
Epoch 450, Loss: 0.9197


In [2]:
import numpy as np

def relu(x):
    return np.maximum(0, x)

def mse(y_true, y_pred):
    return np.mean((y_true - y_pred) ** 2)

np.random.seed(0)
m, d, k = 100, 6, 2
X = np.random.randn(m, d)
Y = np.random.randn(m, k)

hidden_size = 4
W0 = np.random.randn(d, hidden_size) * 0.1
b0 = np.zeros((1, hidden_size))
W1 = np.random.randn(hidden_size, k) * 0.1
b1 = np.zeros((1, k))

Z1 = X @ W0 + b0
A1 = relu(Z1)
Z2 = A1 @ W1 + b1
Y_pred = Z2

empirical_risk = mse(Y, Y_pred)
print("Empirical Risk (MSE):", empirical_risk)

Empirical Risk (MSE): 0.9702897369235239
